// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0eUrmXmNoKbQ4Ty7jYj0S0hdCq9MgvNk',
    appId: '1:118059749074:web:9938f8429f28e15214270b',
    messagingSenderId: '118059749074',
    projectId: 'gogoduck-c3e88',
    authDomain: 'gogoduck-c3e88.firebaseapp.com',
    databaseURL: 'https://gogoduck-c3e88-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'gogoduck-c3e88.firebasestorage.app',
    measurementId: 'G-5DSLCK07D8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWFbgg5RvF78CO20smKLumWThzVPf5mxg',
    appId: '1:118059749074:android:ecbd3a1c27badd4b14270b',
    messagingSenderId: '118059749074',
    projectId: 'gogoduck-c3e88',
    databaseURL: 'https://gogoduck-c3e88-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'gogoduck-c3e88.firebasestorage.app',
  );

}